# Environment Variable Map
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-configmap
    helm.sh/chart: {{ include "dragonchain-k8s.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: dragonchain
    app.kubernetes.io/component: configmap
    app.kubernetes.io/version: {{ .Values.dragonchain.image.version }}
    dragonchainId: {{ .Values.global.environment.INTERNAL_ID }}
data:
{{- if .Values.aws }}
{{- if and .Values.aws.access_key_id .Values.aws.secret_key }}
  AWS_ACCESS_KEY_ID: "{{ .Values.aws.access_key_id }}"
  AWS_SECRET_ACCESS_KEY: "{{ .Values.aws.secret_key }}"
{{- end }}
{{- if .Values.aws.region }}
  AWS_DEFAULT_REGION: "{{ .Values.aws.region }}"
{{- end }}
{{- if .Values.aws.error_reporting_topic }}
  TOPIC_ARN: "{{ .Values.aws.error_reporting_topic }}"
{{- end }}
{{- end }}
  # These allow getting credentials to be more forgiving becuase kiam has a race condition
  AWS_METADATA_SERVICE_TIMEOUT: "5"
  AWS_METADATA_SERVICE_NUM_ATTEMPTS: "20"
  # End kiam Environment Variables
  HASH: blake2b
  ENCRYPTION: secp256k1
  PROOF_SCHEME: trust
  REDIS_PORT: "6379"
  WEB_PORT: "8080"
  RATE_LIMIT: "0"
  REDIS_ENDPOINT: "{{ .Release.Name }}-pr-service"
  REDISEARCH_ENDPOINT: "{{ .Release.Name }}-rs-service"
  LRU_REDIS_ENDPOINT: "{{ .Release.Name }}-cr-service"
  REGISTRY: "{{ .Values.dragonchain.image.registry }}"
  FAAS_GATEWAY: "{{ .Values.faas.gateway }}"
  FAAS_REGISTRY: "{{ .Values.faas.registry }}"
  NAMESPACE: "{{ .Release.Namespace }}"
  STACK_NAME: "d-{{ .Values.global.environment.INTERNAL_ID }}-{{ .Values.global.environment.STAGE }}"
  DEPLOYMENT_NAME: "{{ .Release.Name }}"
  ERROR_REPORTING_TYPE: "{{ .Values.dragonchain.reporting_type }}"
  DRAGONCHAIN_NAME: "{{ .Values.global.environment.DRAGONCHAIN_NAME }}"
  DRAGONCHAIN_VERSION: "{{ .Values.dragonchain.image.version }}"
  DRAGONCHAIN_ENDPOINT: "{{ .Values.global.environment.DRAGONCHAIN_ENDPOINT }}"
  NETWORK: "{{ .Values.global.environment.NETWORK }}"
  BROADCAST_INTERVAL: "{{ .Values.global.environment.BROADCAST_INTERVAL }}"
  INTERCHAIN_WALLET: "{{ .Values.global.environment.INTERCHAIN_WALLET }}"
{{- if .Values.dragonchain.verificationNotification }}
  VERIFICATION_NOTIFICATION: {{ .Values.dragonchain.verificationNotification | toJson | quote }}
{{- end }}
  INTERCHAIN_WALLET: "{{ .Values.global.environment.INTERCHAIN_WALLET }}"
{{- if .Values.faas.registry_username }}
  REGISTRY_USERNAME: "{{ .Values.faas.registry_username }}"
{{- end }}
{{- if .Values.faas.registry_username }}
  REGISTRY_PASSWORD: "{{ .Values.faas.registry_password }}"
{{- end }}
{{- if .Values.dragonchain.storage }}
  STORAGE_TYPE: disk
  STORAGE_LOCATION: "{{ .Values.dragonchain.storage.mount }}"
{{- else }}
  STORAGE_TYPE: s3
  STORAGE_LOCATION: "{{ .Values.global.environment.STORAGE_LOCATION }}"
{{- end }}
  SECRET_LOCATION: "{{ .Values.secret.mountPath }}/{{ .Values.secret.name }}"
{{ toYaml .Values.global.environment | indent 2 }}
---
# Persistent Redis Config Map
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-pr-configmap
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-pr-configmap
    helm.sh/chart: {{ include "dragonchain-k8s.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: dragonchain
    app.kubernetes.io/component: persistent-redis-configmap
    app.kubernetes.io/version: {{ .Values.dragonchain.image.version }}
    dragonchainId: {{ .Values.global.environment.INTERNAL_ID }}
data:
  redis-config: |
    save 900 1
    save 300 10
    save 60 10000
    stop-writes-on-bgsave-error yes
    rdbcompression yes
    rdbchecksum yes
    dbfilename dump.rdb
    appendonly yes
    appendfilename "redis.aof"
    appendfsync everysec
    no-appendfsync-on-rewrite no
    auto-aof-rewrite-percentage 100
    auto-aof-rewrite-min-size 64mb
    aof-load-truncated yes
    aof-use-rdb-preamble yes
---
# Redisearch Config Map
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-rs-configmap
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-rs-configmap
    helm.sh/chart: {{ include "dragonchain-k8s.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: dragonchain
    app.kubernetes.io/component: redisearch-configmap
    app.kubernetes.io/version: {{ .Values.dragonchain.image.version }}
    dragonchainId: {{ .Values.global.environment.INTERNAL_ID }}
data:
  redis-config: |
    save 900 1
    save 300 10
    save 60 10000
    stop-writes-on-bgsave-error yes
    rdbcompression yes
    rdbchecksum yes
    dbfilename dump.rdb
    appendonly yes
    appendfilename "redisearch.aof"
    appendfsync everysec
    no-appendfsync-on-rewrite no
    auto-aof-rewrite-percentage 100
    auto-aof-rewrite-min-size 64mb
    aof-load-truncated yes
    aof-use-rdb-preamble yes
    loadmodule /usr/lib/redis/modules/redisearch.so TIMEOUT 2000 ON_TIMEOUT fail
---
# Cache Redis Config Map
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-cr-configmap
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-cr-configmap
    helm.sh/chart: {{ include "dragonchain-k8s.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: dragonchain
    app.kubernetes.io/component: cacheredis-configmap
    app.kubernetes.io/version: {{ .Values.dragonchain.image.version }}
    dragonchainId: {{ .Values.global.environment.INTERNAL_ID }}
data:
  redis-config: |
    appendonly no
    maxmemory 150mb
    maxmemory-policy allkeys-lru
